---
title: "R Notebooks og reproduserbarhet"
subtitle: "Assignment 1 i MSB105 Data Science - innleveringsfrist 21.09.20"
author: 
  - Katrine Hope
  - Karl-Gunnar Severinsen
classoption: twoside
fontsize: 12pt
output:
  html_document:
    df_print: paged
    toc: true
    toc_depth: 3
  pdf_document:
    df_print: paged
    toc: true
    toc_depth: 3
  word_document:
    df_print: paged
    toc: true
    toc_depth: 3
linestretch: 1.5
bibliography: reproducibility.bib
lang: nb-NO
---


## 1. Innledning

Første test inkludert en referanse: @xie2015

## 2. Teori

### 2.1 Replikerbarhet/reproduserbarhet

Det er ønskelig at vitenskapelige oppdagelser og fremskritt skal være robuste og pålitelige fordi vi ønsker å ha tillit til at resultatene er riktig og at undersøkelsene er gjort på en tilfredsstillende måte [@bollen2015].
I følge @mcnutt2014 er det viktig for at vitenskapen skal utvikle seg at funnene baserer seg på troverdige funn.
Mange forskere mener at reproduserbarhet er en viktig fremgangsmåte for å kunne validere funnene sine, men dette har vist seg å være veldig vanskelig å gjennomføre [@mcnutt2014]. 
Noe av det som kan være med å gjøre det vanskelig å reprodusere, men også replikere, er at tidligere studier kan mangle data eller koder, det kan være feil i programvaren som er sendt med, det kan mangle dokumentasjon, samt er det noen forskere som ikke ønsker å gi fra seg sine data og koder på studiene sine. 
National Science Foundation i USA viser til at for at vitenskap skal være robust og pålitelig må funnene være reproduserbar, replikerbart og generaliserbart [@bollen2015]. 
I henhold til National Science Foundation blir de 3 påstandene definert som [@bollen2015]:

- Reproduserbarhet: Å repodusere vil si å gjøre studiet på nytt, med de samme dataene og med den samme metodikken, men gjort av en uavhengig part.

- Replikerbarhet: Å replikere vil si at et studie gjøres på nytt av en uavhengig part, gjerne med nye data og at resultater og konklusjon er lik som tidligere. 

- Generaliserbarhet: Vil si at et studie kan gjøres på nytt med ny data og ny sammensetning, men komme frem til lignende konklusjoner. 

Reproduksjon har potensiale til å være en minimumsstandard i følge @peng2011, når full uavhengig replikasjon ikke er tilgjengelig. 
Dersom den nye studien kan bekrefte resultatene og konklusjonen fra et tidligere studie via replikasjon blir dette sett på som en vitenskapelig gullstandard [@jasny2011]. 
@peng2011 anser replikasjon som den ultimate standarden i likhet med @jasny2011. 



### 2.2 Problemets omfang

- Vil dagens løsning med arkiv av data og event. programkode hos tidsskriftene
kunne løse problemet?

Ved å integrere koder i selve artikkelen, selv om de ikke trenger nødvendigvis å være synlig, skal det være mulig for andre forskere å reprodusere og replikere studien. Her er en oversikt over hva som skal sendes til tidsskriftene:

- Dokument med tekst.
- Kode til å lese inn dataen med.
- Kode til å kalkulere de ulike modellene. 
- Kode for å teste modellene. 
- Kode for å generere rapport av selve resultatene. 

Hovedpunktet er at all data og koder vil bli sendt sammen med et fullstendig reproduserbart dokument. 

#### 2.2.1 Mulig løsning (teoretisk plan)

- «Compendium», «Dynamic document», «code chunck» og «text chunk»

I følge @gentleman2007 er det viktig, kanskje også essensielt, å integrere beregninger og koder som brukes i dataanalyser, metodebeskrivelser og simuleringer. 
Dette kan gjøres via et kompendium i henhold til @gentleman2007.
Kompendium vil si en samling av de ulike elementene, som tekst, kode, data, metodikk og lignende, og dette skal settes sammen som en enhet for å kunne distribueres, håndteres og oppdateres. 
Dersom kompendiet er laget riktig skal forfattere enkelt kunne reprodusere resultatene. 

Dynamiske dokumenter er en ordnet sammensetning av stykker (chunks) med kode eller tekst. 
Code chunk kan brukes som et middel som gjengir utdata i dokumenter, eller bare for å vise kode for illustrasjon, siden code chunks utfører beregninger som trengs for å produsere riktig utdata i dokumentet, men også for å produsere mellomresultater brukt på tvers av forskjellige code chunks [@gentleman2007]. 
Text chunks er ment å være formatert for lesing og beskriver som oftest problemet, koden, resultatene og tolkningen [@gentleman2007]. 
Et optimalt kompendium vil derfor være et dynamisk dokument siden alle komponenter er til stedet for reproduksjon. 

#### 2.2.2 Mulig løsning:

- R Notebooks

Tidligere var det R markdown som ble brukt, men der fikk man ikke all tekst og koding inn i samme dokument, som oftest ble dette delt opp i ulike vindu. 
R Notebook er den nyeste utgivelsen fra R Studio på programutvikling. Rstudio er en IDE (Integrated Developer Enviroment) for alle R relaterte ting. R Studio er et gratis programvare som du både kan laste ned lokalt på datamaskinen eller du kan jobbe over internett. Alle de vanlige platformene skal ha mulighet til å bruke R Studio som Mac, Window og Linux. R studio må knyttes sammen med andre programvarer for å få maks utbytte av 

Rstudio kan knyttes opp mot git og det gjør at man har arbeidet sitt skylagret. 

## Analyse

## Konklusjon

## Referanse
